# Generated by Django 4.2.7 on 2023-12-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_todoitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(blank=True, default='teesting', max_length=255, null=True),
        ),
    ]
